### ISSUE TITLE
Change max. upload size to any other value

### ISSUE THREAD

**Issue by KingMo5h** [BrandonXLF/details-and-file-uploads#3]
Hello,

it would be nice to have a option to change the max. upload file size to any value. Now its limited to 40mb. But in my case some files are like 100mb or even more.
I coudnt find anything in the installations files to change the value.

**Comment by BrandonXLF** [comment]
@KingMo5h The upload size is set by a PHP variable, so you should be able to modify it on your own. See https://www.wpbeginner.com/wp-tutorials/how-to-increase-the-maximum-file-upload-size-in-wordpress/#edit-php-ini-file-hosting-account.
